-0.5436117648109633

In [22]:
from pyscf import gto, scf, fci

mol = gto.Mole()
mol.verbose = 0
mol.atom = """
    H 0.00000 0.00000 0.00000
    H 0.00000 0.00000 10.00000
"""
mol.basis = "sto3g"
mol.spin = 0
mol.build()

rhf = scf.RHF(mol)
rhf.verbose = 0
rhf.max_cycle = 0
rhf.kernel()

fciobj = fci.FCI(mol, rhf.mo_coeff)
e, c = fciobj.kernel(nroots=10)

import numpy
h = numpy.einsum("e,eab,eij->abij", e, c, c)

c1 = [[1, 0], [0, 0]]
c2 = [[0, 0], [0, 1]]
cc = (c1, c2)
h = numpy.einsum("Iab,Jij,abij->IJ", cc, cc, h)
h

array([[-0.57231959,  0.36084411],
       [ 0.36084411, -0.57231959]])

In [24]:
from pyscf import gto, scf, fci

mol = gto.Mole()
mol.verbose = 0
mol.atom = """
    H 0.00000 0.00000 0.00000
    H 0.00000 0.00000 0.70000
"""
mol.basis = "sto3g"
mol.spin = 0
mol.build()

rhf = scf.RHF(mol)
rhf.verbose = 0
rhf.max_cycle = 0
rhf.kernel()

fciobj = fci.FCI(mol, rhf.mo_coeff)
e, c = fciobj.kernel(nroots=10)

import numpy
h = numpy.einsum("e,eab,eij->abij", e, c, c)

c1 = [[1, 0], [0, 0]]
c2 = [[0, 0], [0, 1]]
cc = (c1, c2)
h = numpy.einsum("Iab,Jij,abij->IJ", cc, cc, h)
h

array([[-1.11734903,  0.17900058],
       [ 0.17900058,  0.56447368]])

In [27]:
numpy.linalg.eig([[0, 10], [10, 10]])

(array([-6.18033989, 16.18033989]),
 array([[-0.85065081, -0.52573111],
        [ 0.52573111, -0.85065081]]))